// 由 backend `cargo run --bin export_types` 產生 — 勿手改

// This file has been generated by Specta. Do not edit this file manually.
/**  `GET /api/admin/categories`（requireAdmin）。裸陣列。admin 版含 created_at、且 JOIN 不過濾 status。 */
export type AdminCategoryRow = {
	id: number,
	name: string,
	slug: string,
	description: string | null,
	short_description: string | null,
	created_at: string,
	updated_at: string | null,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。後台編輯用。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
	description_en: string | null,
	description_ja: string | null,
	description_ko: string | null,
	description_zh_cn: string | null,
	short_description_en: string | null,
	short_description_ja: string | null,
	short_description_ko: string | null,
	short_description_zh_cn: string | null,
};

/**
 *  admin 留言列的一列：comments 表全欄（DB 宣告序）+ LEFT JOIN 的 post_title。
 *  欄位序對齊舊 `row_to_json`（`SELECT c.*` → comments 宣告序，post_title 附在最後）。
 */
export type AdminCommentRow = {
	id: number,
	post_id: number | null,
	author: string,
	content: string,
	likes: number,
	created_at: string,
	is_admin: number,
	email: string | null,
	website: string | null,
	status: string | null,
	ip: string | null,
	parent_id: number | null,
	avatar_url: string | null,
	thought_id: number | null,
	post_title: string | null,
};

export type AdminCommentsResponse = {
	comments: AdminCommentRow[],
	total: number,
	page: number,
	limit: number,
	counts: CommentCounts,
};

/**
 *  `GET /api/admin/posts/:id` 成功回應：`{message, ...row, tags, available_locales}`。
 *  flatten 讓 row 的欄位攤平在頂層，key 序 = message → AdminPostFull 欄位序 → available_locales。
 */
export type AdminPostDetailResponse = {
	message: string,
	available_locales: string[],
} & AdminPostFull;

/**
 *  admin 端點的整列 post（`SELECT p.*` 全欄，含 12 個 i18n 欄）。
 * 
 *  **欄位序 = posts 表宣告序 + tags**，對齊舊 `row_to_json` 的 key 序（serde_json
 *  preserve_order → struct 欄位序即 JSON key 序）。`/api/admin/posts` 與
 *  `/api/admin/posts/:id` 共用；兩者對 excerpt / source_language 的處理不同，由呼叫端覆寫。
 */
export type AdminPostFull = {
	id: number,
	/**  網址用的英文 slug（canonical）。 */
	slug: string | null,
	title: string,
	content: string,
	excerpt: string | null,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	created_at: string,
	updated_at: string | null,
	layout_type: string | null,
	excerpt_zh_cn: string | null,
	title_ja: string | null,
	content_ja: string | null,
	excerpt_ja: string | null,
	title_en: string | null,
	content_en: string | null,
	excerpt_en: string | null,
	source_language: string | null,
	title_zh_cn: string | null,
	content_zh_cn: string | null,
	series_name: string | null,
	series_order: number | null,
	title_ko: string | null,
	content_ko: string | null,
	allow_comments: boolean,
	excerpt_ko: string | null,
	/**  內容格式：'markdown'（預設）| 'mdx'。 */
	format: string | null,
	tags: string[],
};

export type AdminPostsResponse = {
	posts: AdminPostFull[],
	totalPages: number,
	currentPage: number,
	total: number,
};

/**  `GET /api/admin/tags` 單列（admin 版：含 0 篇的 tag、依名排序）。 */
export type AdminTagRow = {
	id: number,
	name: string,
	created_at: string,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。後台編輯用。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
};

/**  `GET /api/admin/users`（**requireOwner**）。`{ users: [...] }`，顯式欄位。 */
export type AdminUserRow = {
	id: number,
	provider: string | null,
	provider_id: string | null,
	display_name: string | null,
	email: string | null,
	avatar_url: string | null,
	role: string | null,
	linked_to: number | null,
	created_at: string | null,
	updated_at: string | null,
};

export type AdminUsersResponse = {
	users: AdminUserRow[],
};

export type AnimeHistoryResponse = {
	message: string,
	history: AnimeRow[],
};

/**  `GET /api/anime/history` 一列。 */
export type AnimeRow = {
	anime_sn: number,
	video_sn: number,
	title: string | null,
	cover_url: string | null,
	episode: string | null,
	tmdb_id: number | null,
	last_watched_at: string | null,
};

export type AudioFeature = {
	id: string,
	energy: number,
	danceability: number,
	valence: number,
};

/**  `GET /api/spotify/audio-features`。順序對齊請求的 ids；查不到的位置是 null。 */
export type AudioFeaturesResponse = {
	audio_features: (AudioFeature | null)[],
};

/**  `GET /api/auth/providers` 回應。兩個 provider 一律都在，用 enabled 區分。 */
export type AuthProvidersResponse = {
	google: OAuthProviderInfo,
	github: OAuthProviderInfo,
};

export type BlacklistResponse = {
	blacklist: BlacklistRow[],
};

/**  `GET /api/admin/blacklist`（requireAdmin）。`{ blacklist: rows }`（SELECT *；目前空表）。 */
export type BlacklistRow = {
	id: number,
	ip: string,
	reason: string | null,
	created_at: string,
};

export type BookDetailResponse = {
	message: string,
	book: BookRow,
};

/**  books 一列（`SELECT *`）。欄位序 = books 表宣告序，對齊舊 `row_to_json` 的 key 序。 */
export type BookRow = {
	id: number,
	isbn: string | null,
	title: string,
	authors: string | null,
	publisher: string | null,
	published_date: string | null,
	description: string | null,
	cover_url: string | null,
	page_count: number | null,
	language: string | null,
	categories: string | null,
	reading_status: string | null,
	rating: number | null,
	personal_notes: string | null,
	date_added: string | null,
	date_updated: string | null,
	date_started: string | null,
	date_finished: string | null,
};

export type BooksListResponse = {
	message: string,
	books: BookRow[],
};

export type CategoriesResponse = {
	message: string,
	categories: CategoryRow[],
};

/**  `GET /api/categories` 單列。欄位順序對齊 Express SELECT。 */
export type CategoryRow = {
	id: number,
	name: string,
	slug: string,
	description: string | null,
	short_description: string | null,
	updated_at: string | null,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。沒填就由前端 fallback 回 name。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
	/**  描述的譯文（tooltip 用）。 */
	description_en: string | null,
	description_ja: string | null,
	description_ko: string | null,
	description_zh_cn: string | null,
	short_description_en: string | null,
	short_description_ja: string | null,
	short_description_ko: string | null,
	short_description_zh_cn: string | null,
};

/**
 *  全站留言的狀態計數（**不受 status/search/post_id 過濾影響**，永遠是全域分佈）。
 *  status 受限於這四種（見 comments.rs 建立邏輯 + admin 審核端點），故可 typed 成固定欄位。
 */
export type CommentCounts = {
	pending: number,
	approved: number,
	spam: number,
	trash: number,
};

/**  comments 一列。欄位順序對齊 live 表實際 `SELECT *` 展開順序。 */
export type CommentRow = {
	id: number,
	post_id: number | null,
	author: string,
	content: string,
	likes: number,
	created_at: string,
	is_admin: number,
	email: string | null,
	website: string | null,
	status: string | null,
	ip: string | null,
	parent_id: number | null,
	avatar_url: string | null,
	thought_id: number | null,
};

export type CommentsResponse = {
	message: string,
	comments: CommentRow[],
};

export type CountResponse = {
	count: number,
};

/**
 *  `GET /api/quote/daily` 的 quote。text/from 兩個來源都是字串：
 *  外部來源走 fetch_quote → Option<(String, String)>，失敗時走 fallback_pool
 *  的 &'static [(&str, &str)]。前端手寫版把 from 標成可選，實際上一定有值。
 */
export type DailyQuote = {
	text: string,
	from: string,
};

/**  `GET /api/quote/daily` */
export type DailyQuoteResponse = {
	message: string,
	quote: DailyQuote,
};

export type DigestComment = {
	id: number,
	author: string,
	content: string,
	created_at: string,
	post_id: number | null,
	thought_id: number | null,
	post_title: string | null,
};

export type DigestPost = {
	id: number,
	slug: string | null,
	title: string,
	category: string | null,
	created_at: string,
};

export type DigestResponse = {
	message: string,
	posts: DigestPost[],
	thoughts: DigestThought[],
	comments: DigestComment[],
	timeline: DigestTimeline[],
};

export type DigestThought = {
	id: number,
	content: string,
	ref_type: string | null,
	created_at: string,
};

export type DigestTimeline = {
	id: number,
	slug: string | null,
	title: string,
	created_at: string,
};

/**
 *  EXIF 的數值欄位在同一份 manifest 裡真的有兩種形狀：舊的 Node builder
 *  （`scripts/builder`）寫 exiftool 的格式化字串（`"f/1.4"`、`"1/640"`、`"32 mm"`），
 *  本檔的 `extract_exif` 寫數字。線上 247 張裡兩種混雜，所以型別得誠實地兩者皆可
 *  ——不是為了寬鬆，是資料真的長這樣。
 */
export type ExifValue = number | string;

/**  `GET /api/films/recent` 一列。 */
export type FilmRow = {
	id: number,
	title: string,
	watched_date: string | null,
	rating: number | null,
	source: string | null,
	tmdb_id: number | null,
	poster_url: string | null,
	backdrop_url: string | null,
	release_year: number | null,
	genres: string | null,
};

export type FilmsResponse = {
	message: string,
	films: FilmRow[],
};

/**  manifest 裡的一張照片。 */
export type GalleryPhoto = {
	id: string,
	title: string,
	description?: string,
	urls: PhotoUrls,
	originalUrl: string,
	thumbnailUrl: string,
	width: number,
	height: number,
	aspectRatio: number,
	size: number,
	format: string,
	/**  舊 builder 產的漸進式佔位圖；本檔不產，但讀到要留著（線上 247 張裡 246 張有） */
	thumbHash: string | null,
	exif: PhotoExif | null,
	/**  epoch 毫秒。舊資料是 EXIF 拍攝時間，缺時退成來源檔 mtime */
	shootTime: number | null,
	tags?: string[],
	tagsEn?: string[],
	gps: PhotoGps | null,
};

/**  `GET /api/admin/keyword-filters`（requireAdmin）。`{ filters: rows }`（SELECT *；目前空表）。 */
export type KeywordFilterRow = {
	id: number,
	keyword: string,
	action: string | null,
	created_at: string,
};

export type KeywordFiltersResponse = {
	filters: KeywordFilterRow[],
};

export type LinkPreviewResponse = {
	/**  目標頁標題（og:title → twitter:title → <title>） */
	title: string | null,
	/**  摘要（og:description → twitter:description → meta description） */
	description: string | null,
	/**  預覽圖（og:image → twitter:image）；沒有就是 None → 前端走降級卡 */
	image: string | null,
	/**  站名（og:site_name），沒有則退回 host */
	site_name: string | null,
	/**  favicon（固定用 /favicon.ico 的絕對路徑，降級卡用） */
	favicon: string | null,
};

export type MetricStat = {
	metric: string,
	count: number,
	p75: number | null,
	good: number,
	needs_improvement: number,
	poor: number,
};

/**  `GET /api/spotify/now-playing`。沒在播 / 未配置 / 抓取失敗一律回 is_playing:false。 */
export type NowPlayingResponse = {
	is_playing: boolean,
	item: SpotifyTrack | null,
	progress_ms: number | null,
};

/**
 *  `GET /api/watch/now` 的 `watching`。原本是 in-memory 的 serde_json::Value，
 *  specta 生不出型別，前端只好手寫一份 LiveNow。
 * 
 *  兩個寫入點（動畫瘋擴充的 heartbeat、Trakt 輪詢）欄位集合本來就一致，
 *  各欄位的正規型別也是確定的，不是猜的：
 *    episode  —— 擴充送的是 `ep ? ep[1] : null`（regex 捕獲組，必為字串）；
 *                anime_history.episode 是 TEXT（anigamer SDK 已正規化成 Option<String>）；
 *                Trakt 那條是 format!("S{:02}E{:02}")。三個來源都是字串。
 *    tmdbId   —— anime_history.tmdb_id 是 INTEGER；Trakt 的 /ids/tmdb 是數字。
 *    progressPct —— 兩條路徑都先 round 成整數才存。
 * 
 *  ⚠ expiresAt 不在這裡：那是伺服器記帳（TTL），不是 API 資料。
 *  舊寫法把它塞進同一個 JSON、serve 時再 remove("expiresAt")，靠「記得移除」維持正確；
 *  現在改由 WatchState 以 (NowWatching, expires_at_ms) 分開存，型別上就不可能洩漏。
 */
export type NowWatching = {
	/**  "anime"（bahamut）/ "movie" / "tv"（trakt） */
	type: string,
	title: string,
	cover: string | null,
	tmdbId: number | null,
	episode: string | null,
	progressPct: number | null,
	/**  "bahamut" | "trakt" */
	source: string,
	externalUrl: string | null,
	/**  epoch ms；與 endsAt 一起給前端做 client 端進度插值 */
	startedAt: number,
	/**  只有 Trakt 那條算得出結束時間；bahamut heartbeat 沒有 */
	endsAt: number | null,
};

/**
 *  單一 OAuth provider 的公開設定。clientId 是公開值（前端組授權 URL 要用），
 *  沒設定時是空字串而不是缺欄位——所以 enabled 才是「這個 provider 能不能用」的判準。
 */
export type OAuthProviderInfo = {
	clientId: string,
	enabled: boolean,
};

export type Pagination = {
	page: number,
	limit: number,
	total: number,
	totalPages: number,
};

/**  exifr `pick` 的那組欄位（key 大小寫照 exifr 原樣，make/model 是小寫的）。 */
export type PhotoExif = {
	make: string | null,
	model: string | null,
	LensModel: string | null,
	FocalLength: ExifValue | null,
	FocalLengthIn35mmFormat: ExifValue | null,
	FNumber: ExifValue | null,
	ExposureTime: ExifValue | null,
	ISO: ExifValue | null,
	DateTimeOriginal: string | null,
	Software: string | null,
	Flash: string | null,
	WhiteBalance: string | null,
	MeteringMode: string | null,
};

/**
 *  只有舊 builder 會寫（線上 247 張裡 2 張有）。三個數字都只從 JSON 讀進來，
 *  而 JSON 表達不了 NaN/Inf，所以是 `number` 而不是 f64 預設的 `number | null`。
 */
export type PhotoGps = {
	latitude: number,
	longitude: number,
	altitude: number | null,
};

/**  同一張照片的四個尺寸；sync 產出時 full/regular 同檔、small/thumb 同檔。 */
export type PhotoUrls = {
	full: string,
	regular: string,
	small: string,
	thumb: string,
};

/**  `GET /api/gallery/photos` */
export type PhotosManifest = {
	version: string,
	generatedAt: string,
	totalPhotos: number,
	photos: GalleryPhoto[],
};

export type PollOptionRow = {
	option_key: string,
	count: number,
};

export type PollResponse = {
	options: PollOptionRow[],
	total: number,
};

/**
 *  `GET /api/posts/:id` 成功回應。欄位序對齊舊 `json!` 的 key 序。
 *  404 路徑（找不到 / 該語系無內容）仍是各自的錯誤 JSON，不走這個型別。
 */
export type PostDetailResponse = {
	message: string,
	id: number,
	/**  canonical 網址用的 slug；前端拿它把非 canonical 的網址 301 過去。 */
	slug: string | null,
	title: string,
	content: string,
	excerpt: string,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	layout_type: string | null,
	allow_comments: boolean,
	/**  內容格式：'markdown'（預設）| 'mdx'。前端據此選渲染管線。 */
	format: string | null,
	series_name: string | null,
	series_order: number | null,
	created_at: string,
	updated_at: string | null,
	locale: string,
	source_language: string,
	is_source: boolean,
	available_locales: string[],
	tags: string[],
};

/**  `GET /api/posts` 的單篇摘要。`title`/`excerpt` 已依 `?lang=` 取好該語系內容。 */
export type PostListItem = {
	id: number,
	slug: string | null,
	title: string,
	excerpt: string,
	/**
	 *  該語系內文的前 260 個 UTF-16 code unit（= JS `content.substring(0,260)`）。
	 *  列表卡片顯示的是內文截斷而非 AI 摘要（見 Blog.tsx NoteCard），但整篇 content
	 *  進列表要多 ~188KB，所以只送前端截斷所需的長度。
	 */
	content_preview: string,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	layout_type: string | null,
	allow_comments: boolean,
	created_at: string,
	updated_at: string | null,
	source_language: string,
	available_locales: string[],
	tags: string[],
};

export type PostsListResponse = {
	message: string,
	posts: PostListItem[],
	locale: string | null,
	pagination: Pagination,
};

export type ReactionRow = {
	emoji: string,
	count: number,
};

export type ReactionsResponse = {
	reactions: ReactionRow[],
};

export type RecentPlayItem = {
	track: SpotifyTrack,
	played_at: string,
};

/**  `GET /api/spotify/recently-played` */
export type RecentlyPlayedResponse = {
	items: RecentPlayItem[],
};

export type SeriesDetailResponse = {
	name: string,
	posts: SeriesPostRow[],
};

export type SeriesListResponse = {
	series: SeriesRow[],
};

/**  `GET /api/series/:name` 單列：某系列下的文章（精簡欄位）。 */
export type SeriesPostRow = {
	id: number,
	title: string,
	excerpt: string | null,
	series_name: string | null,
	series_order: number | null,
	created_at: string,
};

/**  `GET /api/series` 單列：系列名 + 篇數 + 起訖時間。 */
export type SeriesRow = {
	name: string,
	count: number,
	first_at: string | null,
	last_at: string | null,
};

export type SpotifyAlbum = {
	name: string,
	images: SpotifyImage[],
	/**  'YYYY' / 'YYYY-MM' / 'YYYY-MM-DD'（Spotify 依 precision 給不同長度）—— 前端只取年份 */
	release_date: string,
};

export type SpotifyArtist = {
	name: string,
};

export type SpotifyExternalUrls = {
	spotify: string,
};

export type SpotifyImage = {
	url: string,
};

export type SpotifyTrack = {
	id: string,
	name: string,
	artists: SpotifyArtist[],
	album: SpotifyAlbum,
	duration_ms: number,
	external_urls: SpotifyExternalUrls,
	/**  0–100，前端拿來算平均熱門度 */
	popularity: number,
	explicit: boolean,
};

export type StatsResponse = {
	message: string,
	total_posts: number,
	total_chars: number,
	days: number,
};

/**  `GET /api/newsletter/by-token/:token` 的回應（顯式 3 欄）。 */
export type SubscriberByToken = {
	email: string,
	name: string | null,
	status: string | null,
};

/**  `newsletter_subscribers` 一列（`SELECT *`）。欄位序 = 表宣告序，對齊舊 `row_to_json`。 */
export type SubscriberRow = {
	id: number,
	email: string,
	name: string | null,
	status: string | null,
	subscribed_at: string | null,
	unsubscribed_at: string | null,
	unsubscribe_token: string | null,
};

export type SubscribersResponse = {
	message: string,
	subscribers: SubscriberRow[],
	pagination: Pagination,
};

/**
 *  公開標籤列表的單列。欄位順序 = SELECT 欄位順序 = Express JSON key 順序，
 *  以確保 byte-level 對拍等價（serde 依宣告順序序列化）。
 *  One row of the public tag list. Field order = SELECT column order = Express JSON key
 *  order, so serialization is byte-equivalent (serde serializes in declaration order).
 */
export type TagRow = {
	id: number,
	name: string,
	/**
	 *  直接保留 sqlite 原始 TEXT（例 `"2026-04-04 19:16:29"`），不經 chrono 解析，
	 *  避免格式漂移（Express 也是原樣丟出 DATETIME 字串）。
	 */
	created_at: string,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。沒填就由前端 fallback 回 name。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
};

export type TagsResponse = {
	message: string,
	tags: TagRow[],
};

export type ThoughtDetailResponse = {
	message: string,
	thought: ThoughtOut,
};

/**  對外輸出的 thought：欄位順序 = Express `{ ...r, edited, ref }` 後的實際 key 順序。 */
export type ThoughtOut = {
	id: number,
	content: string,
	ref_type: string | null,
	ref_url: string | null,
	ref_json: string | null,
	likes: number,
	created_at: string,
	updated_at: string | null,
	edited: boolean,
	dislikes: number,
	comment_count: number,
	/**  Express 的 `ref: safeParse(r.ref_json)`：解析成功→物件、失敗或 null→JSON null。 */
	ref: ThoughtRef | null,
};

/**  `POST /api/thoughts/:id/react` 的回應。 */
export type ThoughtReactResponse = {
	message: string,
	likes: number,
	dislikes: number,
};

/**
 *  `ref_json` 解析後的物件。這欄不是自由格式——本 repo 裡只有兩個產生者：
 *    - `unfurl_url`（`ref_type="link"`）→ title / desc / image / site
 *    - `enrich_media_ref`（`ref_type="media"`）→ source / url / title / overview /
 *      rating / genres / year / poster，外加呼叫端 `ref.json` 帶進來的
 *      kind / mediaType / tmdbId（那三個 enrich 只是 spread 過去，自己不產）
 * 
 *  線上 5 則碎念裡 2 則有 ref，兩則都是 link。media 這條路目前沒有任何 client
 *  走得到（MCP 只送 content/refUrl/clearRef），欄位是照 enrich_media_ref 的
 *  實作列的，不是猜的。
 * 
 *  未列到的 key 會在 `ref` 裡被丟掉，但同一個回應的 `ref_json` 是原封不動的
 *  字串，所以資料不會不見。
 */
export type ThoughtRef = {
	title: string | null,
	desc: string | null,
	image: string | null,
	site: string | null,
	kind: string | null,
	url: string | null,
	source: string | null,
	overview: string | null,
	genres: string | null,
	poster: string | null,
	mediaType: string | null,
	rating: ThoughtRefScalar | null,
	year: ThoughtRefScalar | null,
	tmdbId: ThoughtRefScalar | null,
};

/**
 *  `ref` 裡少數幾個「字串或數字都可能」的欄位。enrich 自己寫的是字串
 *  （`rating` 走 `format!("{:.1}")`、`year` 取日期前 4 碼），但同一個 key 也可能
 *  來自呼叫端 `ref.json` 的原值，那邊沒有任何東西保證它是字串。
 * 
 *  與 gallery 的 `ExifValue` 刻意各自一份：兩邊的 union 是不同原因造成的
 *  （那邊是兩個寫入端格式不同，這邊是 enrich 覆值與呼叫端原值並存），
 *  綁在一起只會讓其中一邊的註解變成謊話。
 */
export type ThoughtRefScalar = number | string;

export type ThoughtsListResponse = {
	message: string,
	thoughts: ThoughtOut[],
};

/**  `GET /api/watch/tmdb-search` */
export type TmdbSearchResponse = {
	message: string,
	results: TmdbSearchResult[],
};

/**
 *  `GET /api/watch/tmdb-search` 的一列。TMDb 的搜尋回應在這裡重新塑形成前端真正要的
 *  五個欄位（同 spotify 的做法），不是原樣轉發——所以型別就是我們自己的，不是 TMDb 的。
 */
export type TmdbSearchResult = {
	tmdbId: number | null,
	/**  回填請求的 kind（"movie" | "tv"）；TMDb 的 search 端點自己不回這欄 */
	kind: string,
	/**  movie 走 `title`、tv 走 `name`，兩個都沒有才 null */
	title: string | null,
	/**  release_date / first_air_date 的前 4 碼 */
	year: number | null,
	poster: string | null,
};

export type TopGenre = {
	genre: string,
	count: number,
};

/**  `GET /api/spotify/top-genres` */
export type TopGenresResponse = {
	genres: TopGenre[],
};

/**  `GET /api/spotify/top-tracks` */
export type TopTracksResponse = {
	items: SpotifyTrack[],
};

export type TvResponse = {
	message: string,
	series: TvRow[],
};

/**  `GET /api/tv/recent` 一列（GROUP BY series_name 聚合）。 */
export type TvRow = {
	series_name: string,
	last_watched: string | null,
	ep_count: number,
	tmdb_id: number | null,
	poster_url: string | null,
	genres: string | null,
	source: string | null,
};

/**
 *  `GET /api/watch/favorites` 的一列：DB 的 watch_favorites + TMDb 即時在地化。
 *  year 兩個來源都是整數（TMDb 那條走 js_parse_int_opt、DB 欄位是 INTEGER），
 *  所以不是前端手寫版本猜的 string | number。
 */
export type WatchFavoriteRow = {
	id: number,
	/**  "film" | "tv" */
	kind: string,
	tmdbId: number | null,
	rating: number | null,
	quote: string | null,
	/**  TMDb 在地化標題；查不到時退成 `#<tmdbId>`，所以一定有值 */
	title: string,
	poster: string | null,
	year: number | null,
	externalUrl: string,
};

/**  `GET /api/watch/favorites` */
export type WatchFavoritesResponse = {
	message: string,
	favorites: WatchFavoriteRow[],
};

/**  `GET /api/watch/now` */
export type WatchNowResponse = {
	watching: NowWatching | null,
};

/**  `GET /api/watch/stats` —— 5 個 count（key 為 camelCase）。 */
export type WatchStatsResponse = {
	message: string,
	animeCount: number,
	animeEpisodes: number,
	filmCount: number,
	tvSeriesCount: number,
	tvEpisodes: number,
};
