// 由 backend `cargo run --bin export_types` 產生 — 勿手改

// This file has been generated by Specta. Do not edit this file manually.
/**  `GET /api/admin/categories`（requireAdmin）。裸陣列。admin 版含 created_at、且 JOIN 不過濾 status。 */
export type AdminCategoryRow = {
	id: number,
	name: string,
	slug: string,
	description: string | null,
	short_description: string | null,
	created_at: string,
	updated_at: string | null,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。後台編輯用。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
	description_en: string | null,
	description_ja: string | null,
	description_ko: string | null,
	description_zh_cn: string | null,
	short_description_en: string | null,
	short_description_ja: string | null,
	short_description_ko: string | null,
	short_description_zh_cn: string | null,
};

/**
 *  admin 留言列的一列：comments 表全欄（DB 宣告序）+ LEFT JOIN 的 post_title。
 *  欄位序對齊舊 `row_to_json`（`SELECT c.*` → comments 宣告序，post_title 附在最後）。
 */
export type AdminCommentRow = {
	id: number,
	post_id: number | null,
	author: string,
	content: string,
	likes: number,
	created_at: string,
	is_admin: number,
	email: string | null,
	website: string | null,
	status: string | null,
	ip: string | null,
	parent_id: number | null,
	avatar_url: string | null,
	thought_id: number | null,
	post_title: string | null,
};

export type AdminCommentsResponse = {
	comments: AdminCommentRow[],
	total: number,
	page: number,
	limit: number,
	counts: CommentCounts,
};

/**
 *  `GET /api/admin/posts/:id` 成功回應：`{message, ...row, tags, available_locales}`。
 *  flatten 讓 row 的欄位攤平在頂層，key 序 = message → AdminPostFull 欄位序 → available_locales。
 */
export type AdminPostDetailResponse = {
	message: string,
	available_locales: string[],
} & AdminPostFull;

/**
 *  admin 端點的整列 post（`SELECT p.*` 全欄，含 12 個 i18n 欄）。
 * 
 *  **欄位序 = posts 表宣告序 + tags**，對齊舊 `row_to_json` 的 key 序（serde_json
 *  preserve_order → struct 欄位序即 JSON key 序）。`/api/admin/posts` 與
 *  `/api/admin/posts/:id` 共用；兩者對 excerpt / source_language 的處理不同，由呼叫端覆寫。
 */
export type AdminPostFull = {
	id: number,
	/**  網址用的英文 slug（canonical）。 */
	slug: string | null,
	title: string,
	content: string,
	excerpt: string | null,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	created_at: string,
	updated_at: string | null,
	layout_type: string | null,
	excerpt_zh_cn: string | null,
	title_ja: string | null,
	content_ja: string | null,
	excerpt_ja: string | null,
	title_en: string | null,
	content_en: string | null,
	excerpt_en: string | null,
	source_language: string | null,
	title_zh_cn: string | null,
	content_zh_cn: string | null,
	series_name: string | null,
	series_order: number | null,
	title_ko: string | null,
	content_ko: string | null,
	allow_comments: boolean,
	excerpt_ko: string | null,
	/**  內容格式：'markdown'（預設）| 'mdx'。 */
	format: string | null,
	tags: string[],
};

export type AdminPostsResponse = {
	posts: AdminPostFull[],
	totalPages: number,
	currentPage: number,
	total: number,
};

/**  `GET /api/admin/tags` 單列（admin 版：含 0 篇的 tag、依名排序）。 */
export type AdminTagRow = {
	id: number,
	name: string,
	created_at: string,
	post_count: number,
	/**  顯示用譯名（name 仍是資料鍵）。後台編輯用。 */
	name_en: string | null,
	name_ja: string | null,
	name_ko: string | null,
	name_zh_cn: string | null,
};

/**  `GET /api/admin/users`（**requireOwner**）。`{ users: [...] }`，顯式欄位。 */
export type AdminUserRow = {
	id: number,
	provider: string | null,
	provider_id: string | null,
	display_name: string | null,
	email: string | null,
	avatar_url: string | null,
	role: string | null,
	linked_to: number | null,
	created_at: string | null,
	updated_at: string | null,
};

export type AdminUsersResponse = {
	users: AdminUserRow[],
};

export type AnimeHistoryResponse = {
	message: string,
	history: AnimeRow[],
};

/**  `GET /api/anime/history` 一列。 */
export type AnimeRow = {
	anime_sn: number,
	video_sn: number,
	title: string | null,
	cover_url: string | null,
	episode: string | null,
	tmdb_id: number | null,
	last_watched_at: string | null,
};

/**  `GET /api/auth/providers` 回應。兩個 provider 一律都在，用 enabled 區分。 */
export type AuthProvidersResponse = {
	google: OAuthProviderInfo,
	github: OAuthProviderInfo,
};

export type BlacklistResponse = {
	blacklist: BlacklistRow[],
};

/**  `GET /api/admin/blacklist`（requireAdmin）。`{ blacklist: rows }`（SELECT *；目前空表）。 */
export type BlacklistRow = {
	id: number,
	ip: string,
	reason: string | null,
	created_at: string,
};

export type BookDetailResponse = {
	message: string,
	book: BookRow,
};

/**  books 一列（`SELECT *`）。欄位序 = books 表宣告序，對齊舊 `row_to_json` 的 key 序。 */
export type BookRow = {
	id: number,
	isbn: string | null,
	title: string,
	authors: string | null,
	publisher: string | null,
	published_date: string | null,
	description: string | null,
	cover_url: string | null,
	page_count: number | null,
	language: string | null,
	categories: string | null,
	reading_status: string | null,
	rating: number | null,
	personal_notes: string | null,
	date_added: string | null,
	date_updated: string | null,
	date_started: string | null,
	date_finished: string | null,
};

export type BooksListResponse = {
	message: string,
	books: BookRow[],
};

/**
 *  全站留言的狀態計數（**不受 status/search/post_id 過濾影響**，永遠是全域分佈）。
 *  status 受限於這四種（見 comments.rs 建立邏輯 + admin 審核端點），故可 typed 成固定欄位。
 */
export type CommentCounts = {
	pending: number,
	approved: number,
	spam: number,
	trash: number,
};

/**  comments 一列。欄位順序對齊 live 表實際 `SELECT *` 展開順序。 */
export type CommentRow = {
	id: number,
	post_id: number | null,
	author: string,
	content: string,
	likes: number,
	created_at: string,
	is_admin: number,
	email: string | null,
	website: string | null,
	status: string | null,
	ip: string | null,
	parent_id: number | null,
	avatar_url: string | null,
	thought_id: number | null,
};

export type CommentsResponse = {
	message: string,
	comments: CommentRow[],
};

export type CountResponse = {
	count: number,
};

export type DigestComment = {
	id: number,
	author: string,
	content: string,
	created_at: string,
	post_id: number | null,
	thought_id: number | null,
	post_title: string | null,
};

export type DigestPost = {
	id: number,
	slug: string | null,
	title: string,
	category: string | null,
	created_at: string,
};

export type DigestResponse = {
	message: string,
	posts: DigestPost[],
	thoughts: DigestThought[],
	comments: DigestComment[],
	timeline: DigestTimeline[],
};

export type DigestThought = {
	id: number,
	content: string,
	ref_type: string | null,
	created_at: string,
};

export type DigestTimeline = {
	id: number,
	slug: string | null,
	title: string,
	created_at: string,
};

/**  `GET /api/films/recent` 一列。 */
export type FilmRow = {
	id: number,
	title: string,
	watched_date: string | null,
	rating: number | null,
	source: string | null,
	tmdb_id: number | null,
	poster_url: string | null,
	backdrop_url: string | null,
	release_year: number | null,
	genres: string | null,
};

export type FilmsResponse = {
	message: string,
	films: FilmRow[],
};

/**  `GET /api/admin/keyword-filters`（requireAdmin）。`{ filters: rows }`（SELECT *；目前空表）。 */
export type KeywordFilterRow = {
	id: number,
	keyword: string,
	action: string | null,
	created_at: string,
};

export type KeywordFiltersResponse = {
	filters: KeywordFilterRow[],
};

/**
 *  單一 OAuth provider 的公開設定。clientId 是公開值（前端組授權 URL 要用），
 *  沒設定時是空字串而不是缺欄位——所以 enabled 才是「這個 provider 能不能用」的判準。
 */
export type OAuthProviderInfo = {
	clientId: string,
	enabled: boolean,
};

export type Pagination = {
	page: number,
	limit: number,
	total: number,
	totalPages: number,
};

export type PollOptionRow = {
	option_key: string,
	count: number,
};

export type PollResponse = {
	options: PollOptionRow[],
	total: number,
};

/**
 *  `GET /api/posts/:id` 成功回應。欄位序對齊舊 `json!` 的 key 序。
 *  404 路徑（找不到 / 該語系無內容）仍是各自的錯誤 JSON，不走這個型別。
 */
export type PostDetailResponse = {
	message: string,
	id: number,
	/**  canonical 網址用的 slug；前端拿它把非 canonical 的網址 301 過去。 */
	slug: string | null,
	title: string,
	content: string,
	excerpt: string,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	layout_type: string | null,
	allow_comments: boolean,
	/**  內容格式：'markdown'（預設）| 'mdx'。前端據此選渲染管線。 */
	format: string | null,
	series_name: string | null,
	series_order: number | null,
	created_at: string,
	updated_at: string | null,
	locale: string,
	source_language: string,
	is_source: boolean,
	available_locales: string[],
	tags: string[],
};

/**  `GET /api/posts` 的單篇摘要。`title`/`excerpt` 已依 `?lang=` 取好該語系內容。 */
export type PostListItem = {
	id: number,
	slug: string | null,
	title: string,
	excerpt: string,
	/**
	 *  該語系內文的前 260 個 UTF-16 code unit（= JS `content.substring(0,260)`）。
	 *  列表卡片顯示的是內文截斷而非 AI 摘要（見 Blog.tsx NoteCard），但整篇 content
	 *  進列表要多 ~188KB，所以只送前端截斷所需的長度。
	 */
	content_preview: string,
	category: string | null,
	status: string,
	author: string | null,
	view_count: number,
	likes: number,
	layout_type: string | null,
	allow_comments: boolean,
	created_at: string,
	updated_at: string | null,
	source_language: string,
	available_locales: string[],
	tags: string[],
};

export type PostsListResponse = {
	message: string,
	posts: PostListItem[],
	locale: string | null,
	pagination: Pagination,
};

export type ReactionRow = {
	emoji: string,
	count: number,
};

export type ReactionsResponse = {
	reactions: ReactionRow[],
};

export type SeriesDetailResponse = {
	name: string,
	posts: SeriesPostRow[],
};

export type SeriesListResponse = {
	series: SeriesRow[],
};

/**  `GET /api/series/:name` 單列：某系列下的文章（精簡欄位）。 */
export type SeriesPostRow = {
	id: number,
	title: string,
	excerpt: string | null,
	series_name: string | null,
	series_order: number | null,
	created_at: string,
};

/**  `GET /api/series` 單列：系列名 + 篇數 + 起訖時間。 */
export type SeriesRow = {
	name: string,
	count: number,
	first_at: string | null,
	last_at: string | null,
};

export type StatsResponse = {
	message: string,
	total_posts: number,
	total_chars: number,
	days: number,
};

/**  `GET /api/newsletter/by-token/:token` 的回應（顯式 3 欄）。 */
export type SubscriberByToken = {
	email: string,
	name: string | null,
	status: string | null,
};

/**  `newsletter_subscribers` 一列（`SELECT *`）。欄位序 = 表宣告序，對齊舊 `row_to_json`。 */
export type SubscriberRow = {
	id: number,
	email: string,
	name: string | null,
	status: string | null,
	subscribed_at: string | null,
	unsubscribed_at: string | null,
	unsubscribe_token: string | null,
};

export type SubscribersResponse = {
	message: string,
	subscribers: SubscriberRow[],
	pagination: Pagination,
};

export type TvResponse = {
	message: string,
	series: TvRow[],
};

/**  `GET /api/tv/recent` 一列（GROUP BY series_name 聚合）。 */
export type TvRow = {
	series_name: string,
	last_watched: string | null,
	ep_count: number,
	tmdb_id: number | null,
	poster_url: string | null,
	genres: string | null,
	source: string | null,
};

/**  `GET /api/watch/stats` —— 5 個 count（key 為 camelCase）。 */
export type WatchStatsResponse = {
	message: string,
	animeCount: number,
	animeEpisodes: number,
	filmCount: number,
	tvSeriesCount: number,
	tvEpisodes: number,
};
