/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as BookshelfRouteImport } from './routes/bookshelf'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutSiteRouteImport } from './routes/about-site'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIndexRouteImport } from './routes/watch/index'
import { Route as ThinkingIndexRouteImport } from './routes/thinking/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as WatchLibraryRouteImport } from './routes/watch/library'
import { Route as ThinkingIdRouteImport } from './routes/thinking/$id'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminNotesRouteImport } from './routes/admin/notes'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminArticleGeneratorRouteImport } from './routes/admin/article-generator'
import { Route as LocaleUnsubscribeRouteImport } from './routes/$locale/unsubscribe'
import { Route as LocaleSetupRouteImport } from './routes/$locale/setup'
import { Route as LocalePortfolioRouteImport } from './routes/$locale/portfolio'
import { Route as LocalePhotosRouteImport } from './routes/$locale/photos'
import { Route as LocaleMusicRouteImport } from './routes/$locale/music'
import { Route as LocaleMessagesRouteImport } from './routes/$locale/messages'
import { Route as LocaleHistoryRouteImport } from './routes/$locale/history'
import { Route as LocaleFriendsRouteImport } from './routes/$locale/friends'
import { Route as LocaleBookshelfRouteImport } from './routes/$locale/bookshelf'
import { Route as LocaleActivityRouteImport } from './routes/$locale/activity'
import { Route as LocaleAboutSiteRouteImport } from './routes/$locale/about-site'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as LocaleWatchIndexRouteImport } from './routes/$locale/watch/index'
import { Route as LocaleThinkingIndexRouteImport } from './routes/$locale/thinking/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as LocaleWatchLibraryRouteImport } from './routes/$locale/watch/library'
import { Route as LocaleThinkingIdRouteImport } from './routes/$locale/thinking/$id'
import { Route as LocaleBlogIdRouteImport } from './routes/$locale/blog/$id'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const BookshelfRoute = BookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSiteRoute = AboutSiteRouteImport.update({
  id: '/about-site',
  path: '/about-site',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingIndexRoute = ThinkingIndexRouteImport.update({
  id: '/thinking/',
  path: '/thinking/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLibraryRoute = WatchLibraryRouteImport.update({
  id: '/watch/library',
  path: '/watch/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingIdRoute = ThinkingIdRouteImport.update({
  id: '/thinking/$id',
  path: '/thinking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticleGeneratorRoute = AdminArticleGeneratorRouteImport.update({
  id: '/article-generator',
  path: '/article-generator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleUnsubscribeRoute = LocaleUnsubscribeRouteImport.update({
  id: '/$locale/unsubscribe',
  path: '/$locale/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSetupRoute = LocaleSetupRouteImport.update({
  id: '/$locale/setup',
  path: '/$locale/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePortfolioRoute = LocalePortfolioRouteImport.update({
  id: '/$locale/portfolio',
  path: '/$locale/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePhotosRoute = LocalePhotosRouteImport.update({
  id: '/$locale/photos',
  path: '/$locale/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMusicRoute = LocaleMusicRouteImport.update({
  id: '/$locale/music',
  path: '/$locale/music',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMessagesRoute = LocaleMessagesRouteImport.update({
  id: '/$locale/messages',
  path: '/$locale/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleHistoryRoute = LocaleHistoryRouteImport.update({
  id: '/$locale/history',
  path: '/$locale/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFriendsRoute = LocaleFriendsRouteImport.update({
  id: '/$locale/friends',
  path: '/$locale/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBookshelfRoute = LocaleBookshelfRouteImport.update({
  id: '/$locale/bookshelf',
  path: '/$locale/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityRoute = LocaleActivityRouteImport.update({
  id: '/$locale/activity',
  path: '/$locale/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutSiteRoute = LocaleAboutSiteRouteImport.update({
  id: '/$locale/about-site',
  path: '/$locale/about-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleWatchIndexRoute = LocaleWatchIndexRouteImport.update({
  id: '/$locale/watch/',
  path: '/$locale/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleThinkingIndexRoute = LocaleThinkingIndexRouteImport.update({
  id: '/$locale/thinking/',
  path: '/$locale/thinking/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/$locale/blog/',
  path: '/$locale/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleWatchLibraryRoute = LocaleWatchLibraryRouteImport.update({
  id: '/$locale/watch/library',
  path: '/$locale/watch/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleThinkingIdRoute = LocaleThinkingIdRouteImport.update({
  id: '/$locale/thinking/$id',
  path: '/$locale/thinking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIdRoute = LocaleBlogIdRouteImport.update({
  id: '/$locale/blog/$id',
  path: '/$locale/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/activity': typeof ActivityRoute
  '/bookshelf': typeof BookshelfRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/about-site': typeof LocaleAboutSiteRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/photos': typeof LocalePhotosRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/admin/article-generator': typeof AdminArticleGeneratorRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$id': typeof BlogIdRoute
  '/thinking/$id': typeof ThinkingIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/thinking/$id': typeof LocaleThinkingIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/thinking/': typeof LocaleThinkingIndexRoute
  '/$locale/watch/': typeof LocaleWatchIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/activity': typeof ActivityRoute
  '/bookshelf': typeof BookshelfRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/about-site': typeof LocaleAboutSiteRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/photos': typeof LocalePhotosRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/admin/article-generator': typeof AdminArticleGeneratorRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$id': typeof BlogIdRoute
  '/thinking/$id': typeof ThinkingIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/thinking': typeof ThinkingIndexRoute
  '/watch': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/thinking/$id': typeof LocaleThinkingIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/thinking': typeof LocaleThinkingIndexRoute
  '/$locale/watch': typeof LocaleWatchIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/activity': typeof ActivityRoute
  '/bookshelf': typeof BookshelfRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/about-site': typeof LocaleAboutSiteRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/photos': typeof LocalePhotosRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/unsubscribe': typeof LocaleUnsubscribeRoute
  '/admin/article-generator': typeof AdminArticleGeneratorRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$id': typeof BlogIdRoute
  '/thinking/$id': typeof ThinkingIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/thinking/$id': typeof LocaleThinkingIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/thinking/': typeof LocaleThinkingIndexRoute
  '/$locale/watch/': typeof LocaleWatchIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/about-site'
    | '/activity'
    | '/bookshelf'
    | '/friends'
    | '/history'
    | '/journey'
    | '/messages'
    | '/music'
    | '/photos'
    | '/portfolio'
    | '/setup'
    | '/unsubscribe'
    | '/$locale/about'
    | '/$locale/about-site'
    | '/$locale/activity'
    | '/$locale/bookshelf'
    | '/$locale/friends'
    | '/$locale/history'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/photos'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/unsubscribe'
    | '/admin/article-generator'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/subscribers'
    | '/admin/tags'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$id'
    | '/thinking/$id'
    | '/watch/library'
    | '/$locale/'
    | '/admin/'
    | '/blog/'
    | '/thinking/'
    | '/watch/'
    | '/$locale/blog/$id'
    | '/$locale/thinking/$id'
    | '/$locale/watch/library'
    | '/admin/posts/create'
    | '/$locale/blog/'
    | '/$locale/thinking/'
    | '/$locale/watch/'
    | '/admin/posts/'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-site'
    | '/activity'
    | '/bookshelf'
    | '/friends'
    | '/history'
    | '/journey'
    | '/messages'
    | '/music'
    | '/photos'
    | '/portfolio'
    | '/setup'
    | '/unsubscribe'
    | '/$locale/about'
    | '/$locale/about-site'
    | '/$locale/activity'
    | '/$locale/bookshelf'
    | '/$locale/friends'
    | '/$locale/history'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/photos'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/unsubscribe'
    | '/admin/article-generator'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/subscribers'
    | '/admin/tags'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$id'
    | '/thinking/$id'
    | '/watch/library'
    | '/$locale'
    | '/admin'
    | '/blog'
    | '/thinking'
    | '/watch'
    | '/$locale/blog/$id'
    | '/$locale/thinking/$id'
    | '/$locale/watch/library'
    | '/admin/posts/create'
    | '/$locale/blog'
    | '/$locale/thinking'
    | '/$locale/watch'
    | '/admin/posts'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/about-site'
    | '/activity'
    | '/bookshelf'
    | '/friends'
    | '/history'
    | '/journey'
    | '/messages'
    | '/music'
    | '/photos'
    | '/portfolio'
    | '/setup'
    | '/unsubscribe'
    | '/$locale/about'
    | '/$locale/about-site'
    | '/$locale/activity'
    | '/$locale/bookshelf'
    | '/$locale/friends'
    | '/$locale/history'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/photos'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/unsubscribe'
    | '/admin/article-generator'
    | '/admin/books'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/subscribers'
    | '/admin/tags'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$id'
    | '/thinking/$id'
    | '/watch/library'
    | '/$locale/'
    | '/admin/'
    | '/blog/'
    | '/thinking/'
    | '/watch/'
    | '/$locale/blog/$id'
    | '/$locale/thinking/$id'
    | '/$locale/watch/library'
    | '/admin/posts/create'
    | '/$locale/blog/'
    | '/$locale/thinking/'
    | '/$locale/watch/'
    | '/admin/posts/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AboutSiteRoute: typeof AboutSiteRoute
  ActivityRoute: typeof ActivityRoute
  BookshelfRoute: typeof BookshelfRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  JourneyRoute: typeof JourneyRoute
  MessagesRoute: typeof MessagesRoute
  MusicRoute: typeof MusicRoute
  PhotosRoute: typeof PhotosRoute
  PortfolioRoute: typeof PortfolioRoute
  SetupRoute: typeof SetupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAboutSiteRoute: typeof LocaleAboutSiteRoute
  LocaleActivityRoute: typeof LocaleActivityRoute
  LocaleBookshelfRoute: typeof LocaleBookshelfRoute
  LocaleFriendsRoute: typeof LocaleFriendsRoute
  LocaleHistoryRoute: typeof LocaleHistoryRoute
  LocaleMessagesRoute: typeof LocaleMessagesRoute
  LocaleMusicRoute: typeof LocaleMusicRoute
  LocalePhotosRoute: typeof LocalePhotosRoute
  LocalePortfolioRoute: typeof LocalePortfolioRoute
  LocaleSetupRoute: typeof LocaleSetupRoute
  LocaleUnsubscribeRoute: typeof LocaleUnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogIdRoute: typeof BlogIdRoute
  ThinkingIdRoute: typeof ThinkingIdRoute
  WatchLibraryRoute: typeof WatchLibraryRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ThinkingIndexRoute: typeof ThinkingIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
  LocaleBlogIdRoute: typeof LocaleBlogIdRoute
  LocaleThinkingIdRoute: typeof LocaleThinkingIdRoute
  LocaleWatchLibraryRoute: typeof LocaleWatchLibraryRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleThinkingIndexRoute: typeof LocaleThinkingIndexRoute
  LocaleWatchIndexRoute: typeof LocaleWatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookshelf': {
      id: '/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof BookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-site': {
      id: '/about-site'
      path: '/about-site'
      fullPath: '/about-site'
      preLoaderRoute: typeof AboutSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/': {
      id: '/thinking/'
      path: '/thinking'
      fullPath: '/thinking/'
      preLoaderRoute: typeof ThinkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/library': {
      id: '/watch/library'
      path: '/watch/library'
      fullPath: '/watch/library'
      preLoaderRoute: typeof WatchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/$id': {
      id: '/thinking/$id'
      path: '/thinking/$id'
      fullPath: '/thinking/$id'
      preLoaderRoute: typeof ThinkingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/article-generator': {
      id: '/admin/article-generator'
      path: '/article-generator'
      fullPath: '/admin/article-generator'
      preLoaderRoute: typeof AdminArticleGeneratorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/unsubscribe': {
      id: '/$locale/unsubscribe'
      path: '/$locale/unsubscribe'
      fullPath: '/$locale/unsubscribe'
      preLoaderRoute: typeof LocaleUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/setup': {
      id: '/$locale/setup'
      path: '/$locale/setup'
      fullPath: '/$locale/setup'
      preLoaderRoute: typeof LocaleSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/portfolio': {
      id: '/$locale/portfolio'
      path: '/$locale/portfolio'
      fullPath: '/$locale/portfolio'
      preLoaderRoute: typeof LocalePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/photos': {
      id: '/$locale/photos'
      path: '/$locale/photos'
      fullPath: '/$locale/photos'
      preLoaderRoute: typeof LocalePhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/music': {
      id: '/$locale/music'
      path: '/$locale/music'
      fullPath: '/$locale/music'
      preLoaderRoute: typeof LocaleMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/messages': {
      id: '/$locale/messages'
      path: '/$locale/messages'
      fullPath: '/$locale/messages'
      preLoaderRoute: typeof LocaleMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/history': {
      id: '/$locale/history'
      path: '/$locale/history'
      fullPath: '/$locale/history'
      preLoaderRoute: typeof LocaleHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/friends': {
      id: '/$locale/friends'
      path: '/$locale/friends'
      fullPath: '/$locale/friends'
      preLoaderRoute: typeof LocaleFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/bookshelf': {
      id: '/$locale/bookshelf'
      path: '/$locale/bookshelf'
      fullPath: '/$locale/bookshelf'
      preLoaderRoute: typeof LocaleBookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity': {
      id: '/$locale/activity'
      path: '/$locale/activity'
      fullPath: '/$locale/activity'
      preLoaderRoute: typeof LocaleActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about-site': {
      id: '/$locale/about-site'
      path: '/$locale/about-site'
      fullPath: '/$locale/about-site'
      preLoaderRoute: typeof LocaleAboutSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/watch/': {
      id: '/$locale/watch/'
      path: '/$locale/watch'
      fullPath: '/$locale/watch/'
      preLoaderRoute: typeof LocaleWatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/thinking/': {
      id: '/$locale/thinking/'
      path: '/$locale/thinking'
      fullPath: '/$locale/thinking/'
      preLoaderRoute: typeof LocaleThinkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/$locale/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/watch/library': {
      id: '/$locale/watch/library'
      path: '/$locale/watch/library'
      fullPath: '/$locale/watch/library'
      preLoaderRoute: typeof LocaleWatchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/thinking/$id': {
      id: '/$locale/thinking/$id'
      path: '/$locale/thinking/$id'
      fullPath: '/$locale/thinking/$id'
      preLoaderRoute: typeof LocaleThinkingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$id': {
      id: '/$locale/blog/$id'
      path: '/$locale/blog/$id'
      fullPath: '/$locale/blog/$id'
      preLoaderRoute: typeof LocaleBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminArticleGeneratorRoute: typeof AdminArticleGeneratorRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminArticleGeneratorRoute: AdminArticleGeneratorRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AboutSiteRoute: AboutSiteRoute,
  ActivityRoute: ActivityRoute,
  BookshelfRoute: BookshelfRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  JourneyRoute: JourneyRoute,
  MessagesRoute: MessagesRoute,
  MusicRoute: MusicRoute,
  PhotosRoute: PhotosRoute,
  PortfolioRoute: PortfolioRoute,
  SetupRoute: SetupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAboutSiteRoute: LocaleAboutSiteRoute,
  LocaleActivityRoute: LocaleActivityRoute,
  LocaleBookshelfRoute: LocaleBookshelfRoute,
  LocaleFriendsRoute: LocaleFriendsRoute,
  LocaleHistoryRoute: LocaleHistoryRoute,
  LocaleMessagesRoute: LocaleMessagesRoute,
  LocaleMusicRoute: LocaleMusicRoute,
  LocalePhotosRoute: LocalePhotosRoute,
  LocalePortfolioRoute: LocalePortfolioRoute,
  LocaleSetupRoute: LocaleSetupRoute,
  LocaleUnsubscribeRoute: LocaleUnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogIdRoute: BlogIdRoute,
  ThinkingIdRoute: ThinkingIdRoute,
  WatchLibraryRoute: WatchLibraryRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ThinkingIndexRoute: ThinkingIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
  LocaleBlogIdRoute: LocaleBlogIdRoute,
  LocaleThinkingIdRoute: LocaleThinkingIdRoute,
  LocaleWatchLibraryRoute: LocaleWatchLibraryRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleThinkingIndexRoute: LocaleThinkingIndexRoute,
  LocaleWatchIndexRoute: LocaleWatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
